modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/AlaharranHonor/StarWormLightingMod"
logoFile="logo.png"
credits="${mod_credits}"
authors="${mod_authors}"
description="${mod_description}"

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="swdm"
    type="OPTIONAL"
    versionRange="[0,)"
    ordering="AFTER" # Load after to allow addon blocks to be registered first
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="swem"
    type="OPTIONAL"
    versionRange="[0,)"
    ordering="AFTER" # Load after to allow addon blocks to be registered first
    side="BOTH"